import = [
  "~/.config/alacritty/themes/dark_horizon.toml"
]

[window]
decorations = "none" # No title bar
padding = { x = 1, y = 9 } # for monitor
# padding = { x = 1, y = 6 } # for laptop

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11.0 # for monitor
# size = 8.0 # for laptop
offset = { x = 0, y = 0 } # for monitor
# offset = { x = 1, y = 0 } # for laptop

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
# Ctrl+Backspace fix
chars = "\u0017"
key = "Back"
mods = "Control"

[cursor]
style = "Block"          # Options: "Block", "Underline", "Beam"
